name: Pull Request checks

on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  terraform-fmt:
    name: Terraform Formatting
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: setup terraform
      uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 #v3.0.0
    - name: terraform fmt
      run: terraform fmt -check -diff -recursive ./

  terraform-validate:
    name: Terraform config validation
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: setup terraform
      uses: hashicorp/setup-terraform@a1502cd9e758c50496cc9ac5308c4843bcd56d36 #v3.0.0
    - name: terraform init
      run: terraform init
    - name: terraform validate
      run: terraform validate

  tflint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - name: cache tflint
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ~/.tflint.d/plugins
        key: tflint-${{ hashFiles('.tflint.hcl') }}
    - name: setup tflint
      uses: terraform-linters/setup-tflint@3bb7d777f5c38e288977551bc117a79437bdc6fd # v3.1.0
    - name: tflint init
      run: tflint --init
    - name: tflint validate
      run: tflint -f compact --module
